import '../models/scout_report.dart';
import '../models/user.dart';
import '../models/dashboard_stats.dart';

/// Mock data service that provides sample data for the admin panel
class MockDataService {
  static final MockDataService _instance = MockDataService._internal();
  factory MockDataService() => _instance;
  MockDataService._internal();

  /// Generate mock scout reports
  List<ScoutReport> getScoutReports() {
    return [
      ScoutReport(
        id: '1',
        playerId: 'p1',
        playerName: 'Arda Güler',
        playerPosition: 'Orta Saha',
        playerAge: 19,
        playerTeam: 'Real Madrid',
        matchDate: DateTime.now().subtract(const Duration(days: 2)),
        rivalTeam: 'Barcelona',
        score: '2-1',
        minutePlayed: 67,
        matchType: 'Stadyum',
        physicalRating: 7,
        physicalDescription: 'Çevik ve hızlı, iyi denge',
        technicalRating: 9,
        technicalDescription: 'Mükemmel top kontrolü ve şutu',
        tacticalRating: 9,
        tacticalDescription: 'Oyun okuması çok iyi, pozisyon bulma yeteneği yüksek',
        mentalRating: 8,
        mentalDescription: 'Baskı altında sakin, lider karakteri var',
        overallRating: 8.5,
        potentialRating: 9.5,
        strengths: 'Yaratıcılık, pas yeteneği, şut tekniği',
        weaknesses: 'Fiziksel dayanıklılık geliştirilmeli',
        risks: 'Sakatlık geçmişi',
        recommendedRole: 'Playmaker veya sağ kanat',
        scoutId: 's1',
        scoutName: 'Ahmet Yılmaz',
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        description: 'Olağanüstü yetenekli genç oyuncu',
        imageUrls: [],
        status: 'submitted',
      ),
      ScoutReport(
        id: '2',
        playerId: 'p2',
        playerName: 'Kenan Yıldız',
        playerPosition: 'Sol Kanat',
        playerAge: 19,
        playerTeam: 'Juventus',
        matchDate: DateTime.now().subtract(const Duration(days: 5)),
        rivalTeam: 'AC Milan',
        score: '1-0',
        minutePlayed: 90,
        matchType: 'TV',
        physicalRating: 7,
        physicalDescription: 'Hızlı ve çevik',
        technicalRating: 9,
        technicalDescription: 'Çok iyi dripling',
        tacticalRating: 7,
        tacticalDescription: 'Kanat oyununda etkili',
        mentalRating: 8,
        mentalDescription: 'Genç yaşına rağmen olgun',
        overallRating: 7.8,
        potentialRating: 9.0,
        strengths: 'Bire bir pozisyonlarda etkili',
        weaknesses: 'Defansif katkı az',
        risks: 'Düşük',
        recommendedRole: 'Sol kanat veya 10 numara',
        scoutId: 's2',
        scoutName: 'Mehmet Kaya',
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
        description: 'Gelecek vaat eden kanat oyuncusu',
        imageUrls: [],
        status: 'submitted',
      ),
      ScoutReport(
        id: '3',
        playerId: 'p3',
        playerName: 'Ferdi Kadıoğlu',
        playerPosition: 'Sol Bek',
        playerAge: 24,
        playerTeam: 'Brighton',
        matchDate: DateTime.now().subtract(const Duration(days: 7)),
        rivalTeam: 'Chelsea',
        score: '1-1',
        minutePlayed: 90,
        matchType: 'TV',
        physicalRating: 8,
        physicalDescription: 'Güçlü ve dayanıklı',
        technicalRating: 8,
        technicalDescription: 'İyi kros ve pas',
        tacticalRating: 8,
        tacticalDescription: 'Hem hücum hem savunmada dengeli',
        mentalRating: 8,
        mentalDescription: 'Çok çalışkan ve disiplinli',
        overallRating: 8.0,
        potentialRating: 8.5,
        strengths: 'İki yönlü oynama yeteneği',
        weaknesses: 'Hava toplarında ortalama',
        risks: 'Düşük',
        recommendedRole: 'Modern full-back',
        scoutId: 's1',
        scoutName: 'Ahmet Yılmaz',
        createdAt: DateTime.now().subtract(const Duration(days: 6)),
        description: 'Çok yönlü defans oyuncusu',
        imageUrls: [],
        status: 'approved',
      ),
      ScoutReport(
        id: '4',
        playerId: 'p4',
        playerName: 'Orkun Kökçü',
        playerPosition: 'Orta Saha',
        playerAge: 23,
        playerTeam: 'Benfica',
        matchDate: DateTime.now().subtract(const Duration(days: 10)),
        rivalTeam: 'Porto',
        score: '3-2',
        minutePlayed: 90,
        matchType: 'TV',
        physicalRating: 7,
        physicalDescription: 'Orta seviye',
        technicalRating: 9,
        technicalDescription: 'Mükemmel duran top ve uzun pas',
        tacticalRating: 9,
        tacticalDescription: 'Oyun kurma yeteneği çok iyi',
        mentalRating: 9,
        mentalDescription: 'Lider, kaptan karakteri',
        overallRating: 8.5,
        potentialRating: 9.0,
        strengths: 'Set parçaları, uzun pas, şut',
        weaknesses: 'Hız biraz düşük',
        risks: 'Düşük',
        recommendedRole: 'Merkez orta saha',
        scoutId: 's3',
        scoutName: 'Can Demir',
        createdAt: DateTime.now().subtract(const Duration(days: 9)),
        description: 'Kaptan kalitesinde playmaker',
        imageUrls: [],
        status: 'approved',
      ),
      ScoutReport(
        id: '5',
        playerId: 'p5',
        playerName: 'Semih Kılıçsoy',
        playerPosition: 'Forvet',
        playerAge: 18,
        playerTeam: 'Beşiktaş',
        matchDate: DateTime.now().subtract(const Duration(days: 3)),
        rivalTeam: 'Galatasaray',
        score: '2-2',
        minutePlayed: 75,
        matchType: 'Stadyum',
        physicalRating: 8,
        physicalDescription: 'Güçlü ve hızlı',
        technicalRating: 7,
        technicalDescription: 'İyi şut tekniği',
        tacticalRating: 6,
        tacticalDescription: 'Ceza sahası içinde etkili',
        mentalRating: 7,
        mentalDescription: 'Gol içgüdüsü var',
        overallRating: 7.0,
        potentialRating: 8.5,
        strengths: 'Gol yeteneği, fiziksel güç',
        weaknesses: 'Pas oyununda gelişmeli',
        risks: 'Orta - adaptasyon süreci',
        recommendedRole: 'Merkez forvet',
        scoutId: 's2',
        scoutName: 'Mehmet Kaya',
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
        description: 'Gol kokulu genç forvet',
        imageUrls: [],
        status: 'submitted',
      ),
      ScoutReport(
        id: '6',
        playerId: 'p6',
        playerName: 'Cengiz Ünder',
        playerPosition: 'Sağ Kanat',
        playerAge: 27,
        playerTeam: 'Fenerbahçe',
        matchDate: DateTime.now().subtract(const Duration(days: 14)),
        rivalTeam: 'Trabzonspor',
        score: '4-1',
        minutePlayed: 78,
        matchType: 'TV',
        physicalRating: 6,
        physicalDescription: 'Hızlı ama sakatlığa yatkın',
        technicalRating: 8,
        technicalDescription: 'Sol ayak şutu mükemmel',
        tacticalRating: 7,
        tacticalDescription: 'Kesme hareketleri etkili',
        mentalRating: 7,
        mentalDescription: 'Özgüveni yüksek',
        overallRating: 7.0,
        potentialRating: 7.5,
        strengths: 'Şut, hız, bire bir',
        weaknesses: 'Sakatlık geçmişi',
        risks: 'Yüksek sakatlık riski',
        recommendedRole: 'Sağ kanat (kesme)',
        scoutId: 's3',
        scoutName: 'Can Demir',
        createdAt: DateTime.now().subtract(const Duration(days: 13)),
        description: 'Deneyimli kanat oyuncusu',
        imageUrls: [],
        status: 'rejected',
      ),
    ];
  }

  /// Generate mock users
  List<AppUser> getUsers() {
    final now = DateTime.now();
    return [
      AppUser(
        id: 'u1',
        name: 'Ahmet Yılmaz',
        email: 'ahmet.yilmaz@email.com',
        role: 'scout',
        createdAt: now.subtract(const Duration(days: 120)),
        lastActiveAt: now.subtract(const Duration(hours: 1)),
        isOnline: true,
        reportCount: 45,
      ),
      AppUser(
        id: 'u2',
        name: 'Mehmet Kaya',
        email: 'mehmet.kaya@email.com',
        role: 'scout',
        createdAt: now.subtract(const Duration(days: 90)),
        lastActiveAt: now.subtract(const Duration(hours: 3)),
        isOnline: true,
        reportCount: 32,
      ),
      AppUser(
        id: 'u3',
        name: 'Can Demir',
        email: 'can.demir@email.com',
        role: 'scout',
        createdAt: now.subtract(const Duration(days: 60)),
        lastActiveAt: now.subtract(const Duration(minutes: 30)),
        isOnline: true,
        reportCount: 28,
      ),
      AppUser(
        id: 'u4',
        name: 'Ayşe Öztürk',
        email: 'ayse.ozturk@email.com',
        role: 'premium',
        createdAt: now.subtract(const Duration(days: 45)),
        lastActiveAt: now.subtract(const Duration(hours: 5)),
        isOnline: false,
        reportCount: 0,
      ),
      AppUser(
        id: 'u5',
        name: 'Fatma Şahin',
        email: 'fatma.sahin@email.com',
        role: 'user',
        createdAt: now.subtract(const Duration(days: 30)),
        lastActiveAt: now.subtract(const Duration(days: 2)),
        isOnline: false,
        reportCount: 0,
      ),
      AppUser(
        id: 'u6',
        name: 'Ali Koç',
        email: 'ali.koc@email.com',
        role: 'premium',
        createdAt: now.subtract(const Duration(days: 25)),
        lastActiveAt: now.subtract(const Duration(hours: 12)),
        isOnline: false,
        reportCount: 0,
      ),
      AppUser(
        id: 'u7',
        name: 'Zeynep Arslan',
        email: 'zeynep.arslan@email.com',
        role: 'user',
        createdAt: now.subtract(const Duration(days: 20)),
        lastActiveAt: now.subtract(const Duration(days: 1)),
        isOnline: false,
        reportCount: 0,
      ),
      AppUser(
        id: 'u8',
        name: 'Mustafa Aydın',
        email: 'mustafa.aydin@email.com',
        role: 'scout',
        createdAt: now.subtract(const Duration(days: 15)),
        lastActiveAt: now.subtract(const Duration(hours: 2)),
        isOnline: true,
        reportCount: 12,
      ),
      AppUser(
        id: 'u9',
        name: 'Elif Çelik',
        email: 'elif.celik@email.com',
        role: 'user',
        createdAt: now.subtract(const Duration(days: 10)),
        lastActiveAt: now.subtract(const Duration(hours: 6)),
        isOnline: false,
        reportCount: 0,
      ),
      AppUser(
        id: 'u10',
        name: 'Burak Yıldırım',
        email: 'burak.yildirim@email.com',
        role: 'premium',
        createdAt: now.subtract(const Duration(days: 5)),
        lastActiveAt: now.subtract(const Duration(minutes: 45)),
        isOnline: true,
        reportCount: 0,
      ),
      AppUser(
        id: 'u11',
        name: 'Deniz Kara',
        email: 'deniz.kara@email.com',
        role: 'user',
        createdAt: now.subtract(const Duration(days: 3)),
        lastActiveAt: now.subtract(const Duration(hours: 8)),
        isOnline: false,
        reportCount: 0,
      ),
      AppUser(
        id: 'u12',
        name: 'Selin Aksu',
        email: 'selin.aksu@email.com',
        role: 'user',
        createdAt: now.subtract(const Duration(days: 1)),
        lastActiveAt: now.subtract(const Duration(hours: 4)),
        isOnline: false,
        reportCount: 0,
      ),
    ];
  }

  /// Get dashboard statistics
  DashboardStats getDashboardStats() {
    final users = getUsers();
    final reports = getScoutReports();
    final now = DateTime.now();

    return DashboardStats(
      totalUsers: users.length,
      dailyActiveUsers: users.where((u) => 
        now.difference(u.lastActiveAt).inHours < 24
      ).length,
      onlineUsers: users.where((u) => u.isOnline).length,
      totalReports: reports.length,
      pendingReports: reports.where((r) => r.status == 'submitted').length,
      approvedReports: reports.where((r) => r.status == 'approved').length,
      rejectedReports: reports.where((r) => r.status == 'rejected').length,
      apiResponseMs: 45,
      dbStatus: true,
      weeklyActivity: List.generate(7, (i) {
        final date = now.subtract(Duration(days: 6 - i));
        return ActivityPoint(
          date: date,
          users: 20 + (i * 5) + (i % 2 == 0 ? 10 : 0),
          reports: 3 + (i % 3),
        );
      }),
    );
  }
}
