// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU-kb-4Fk4YlJkZrWbSy_gwQO0Gpj7aqk',
    appId: '1:471894032716:web:dd2708e9ba72b15c5a8fe9',
    messagingSenderId: '471894032716',
    projectId: 'futveri',
    authDomain: 'futveri.firebaseapp.com',
    storageBucket: 'futveri.firebasestorage.app',
    measurementId: 'G-NDQYN8DSWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_SRaCE23Sl7A5MsyfS4eLqxwkar3eXHg',
    appId: '1:471894032716:android:93ccdf6e59d0c2ee5a8fe9',
    messagingSenderId: '471894032716',
    projectId: 'futveri',
    storageBucket: 'futveri.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDItdpfKsg5q4oE0yplx4wXPuj-9WoIB_U',
    appId: '1:471894032716:ios:e9895dd44293212a5a8fe9',
    messagingSenderId: '471894032716',
    projectId: 'futveri',
    storageBucket: 'futveri.firebasestorage.app',
    iosBundleId: 'com.example.futveri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDItdpfKsg5q4oE0yplx4wXPuj-9WoIB_U',
    appId: '1:471894032716:ios:e9895dd44293212a5a8fe9',
    messagingSenderId: '471894032716',
    projectId: 'futveri',
    storageBucket: 'futveri.firebasestorage.app',
    iosBundleId: 'com.example.futveri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU-kb-4Fk4YlJkZrWbSy_gwQO0Gpj7aqk',
    appId: '1:471894032716:web:03da79211b2e83ab5a8fe9',
    messagingSenderId: '471894032716',
    projectId: 'futveri',
    authDomain: 'futveri.firebaseapp.com',
    storageBucket: 'futveri.firebasestorage.app',
    measurementId: 'G-KEYSDTK1E3',
  );
}
