default_platform(:ios)

platform :ios do
  desc "Flutter projesini derle ve TestFlight'a yukle"
  lane :beta do
    
    # 1. API Key ile Giris
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_FILEPATH"],
      duration: 1200,
      in_house: false
    )

    # 2. Sertifika ve Provisioning Profile Al
    get_certificates(api_key: api_key)
    # App Store icin profile'i indir ve sistemde ayarla
    get_provisioning_profile(
      api_key: api_key,
      app_identifier: "com.futveri.app",
      filename: "appstore.mobileprovision",
      force: true
    )

    # 3. Build Numarasini Arttir (+1 yapar)
    increment_build_number(xcodeproj: "Runner.xcodeproj")

    # 4. Flutter Build Al (IPA Olustur)
    # Manuel signing'i zorlamak icin PROVISIONING_PROFILE_SPECIFIER ve CODE_SIGN_IDENTITY kullaniyoruz
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.futveri.app" => "com.futveri.app AppStore"
        }
      },
      xcargs: "CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='Apple Distribution' PROVISIONING_PROFILE_SPECIFIER='com.futveri.app AppStore'"
    )

    # 4. TestFlight'a Yukle
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end